source "http://rubygems.org"

gem "jekyll", "~> 1.0.0"
gem "sass", "~> 3.2.2"
gem "haml", "~> 4.0.3"
gem "compass", "~> 0.12.2"
gem "RedCloth", "~> 4.2.9"
gem "rdiscount", "~> 2.0"
gem "zurb-foundation", :git => "git@github.com:zurb/foundation.git"
gem "foreman", "~> 0.63.0"
